version: '3.1'

services:
  jrtb-bot:
    depends_on:
      - db
    build:
      context: .
    environment:
      - BOT_NAME=CFGames_bot
      - BOT_TOKEN=1887804860:AAFAI8p1-t6WWwKeyJdHNXa_8du2rRx32Js

    restart: always
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 5432:5432