version: '3.1'

services:
  jrtb-bot:
    depends_on:
      - db
    build:
      context: .
    environment:
      - BOT_NAME=${BOT_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_DB_USERNAME=${BOT_DB_USERNAME}
      - BOT_DB_PASSWORD=${BOT_DB_PASSWORD}
    restart: always
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 5432:5432